pipeline {
  agent any

  environment {
    IMAGE = "level2-image"
  }

  stages {
    stage('Checkout') {
      steps {
        git url: 'https://github.com/anjankumarcr/task-02-devops.git', branch: 'main'
      }
    }

    stage('Build') {
      steps {
        sh 'echo "Building project (Level-02)..."'
      }
    }

    stage('Test') {
      steps {
        sh 'echo "Running tests (placeholder)..."'
      }
    }

    stage('Docker Build') {
      steps {
        sh 'docker build -t ${IMAGE}:v1 . || echo "no Dockerfile or building skipped"'
      }
    }

    stage('Post') {
      steps {
        sh 'echo "Level-02 pipeline finished"'
      }
    }
  }

  post {
    success { echo "Success" }
    failure { echo "Failed" }
  }
}
